package ru.ilnur.verificationmailservice.web.contracts;

public enum ErrorCodes {
    ACCESS_DENIED,
    NOT_VALID_ARGUMENT,
    UNKNOWN_ERROR,
    NOT_FOUND,
    REFRESH_TOKEN_EXPIRED,
    BAD_HTTP_REQUEST,
    INVALID_CODE,
    WRONG_CREDENTIALS,
    ACCOUNT_NOT_VERIFIED,
    EMAIL_ALREADY_USE,
    EXPIRED_REQUEST_CODE,
    REQUEST_CODE_ALREADY_USED,
    UNABLE_SEND_MESSAGE,
    CONTRACTOR_EMAIL_ALREADY_ADD;
}
